// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "kirbyfly1":return img`
........................
........................
........................
........33..............
.......3333333..........
........333f3f..........
.......3333f3f..........
........3f3f3f..........
.........3f333..........
.........22.22..........
........222.22..........
........22.22...........
........................
........................
........................
........................
`;
            case "image2":
            case "INAVDOR":return img`
........................................
......eeeeee............................
.....eeeeeeeee..........................
.....eeeeeeeee..........................
.....eeeeeeeee..........................
....eee55555eee.........................
....eee55555eeeeeeeeeeeeeeeeeeeeee......
....eee55555eeeeeeeeeeeeeeeeeeeeee......
...eeee55555eeeeeeeeeeeeeeeeeeeeee......
...eeee55555eeeeeeeeeeeeeeeeeeeeee......
...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
...eeee55555eeeeeeeeeeeeeeeeeeeeee......
...eeee55555eeeeeeeeeeeeeeeeeeeeee......
....eee55555eeeeeeeeeeeeeeeeeeeeee......
....eee55555eeeeeeeeeeeeeeeeeeeeee......
....eee55555eeeeeeeeeeeeeeeeeeeeee......
....eeeeeeeeee..........................
....eeeeeeeeee..........................
....eeeeeeeeee..........................
.....eeeeee.............................
........................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
